---
title: ''
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)

library(RDS)
library(igraph)
library(ggraph)
```

### SPRTCA Example 

#### Data description
```{r, echo=F}
data <- read.csv("C:/Users/smala/Documents/Thesis/ContinuousAssociationRDS/example/example_data.csv")
```

```{r read data}
#read in data
#data <- read.csv("PATH TO YOUR DATA/example_data.csv")

#first rows of data set
head(data)

#coerce data to RDS data frame (required for analysis)
data_rds <- as.rds.data.frame(df=data,id="id",
                          recruiter.id="rec.id",
                          network.size="degree",
                          population.size=15000)

#check 
str(data)
```


#### Plot RDS data 
```{r plot tree, fig.width=14}
#prep data
edges <- data %>% dplyr::select(rec.id, id) %>% dplyr::filter(rec.id!=0)
edges2 <- as.matrix(edges)
#set up graph object with tree as layout
g1 <- graph_from_edgelist(edges2, directed = T)
V(g1)$disease <- as.character(data$disease)
V(g1)$age <- data$age


#plot tree
ggraph(g1,layout=layout.reingold.tilford(g1, root=c(5,4,3,2,1), rootlevel=c(8,1,15,8,1)) ) + 
#add edges
geom_edge_link(edge_width = .2) +
#add vertices
geom_node_point(size=2, aes(color=disease)) + theme_void() + scale_shape_manual(name = "disease",  values = c(22, 21))+ theme( plot.background = element_rect(fill="white"), legend.position = "top") + scale_color_manual(name="", values=c( "red", "black")) 
```

#### SPRTCA function
```{r}
#Inputs
#iter number of times to randomize data and calculate a test statistic
#var1 character or numeric variable
#var2 character or numeric variable
#net RDS data frame

sprtca <-function(iter, character.var, numeric.var, net){
  #tree data to test
  dat <- net
  dat$numeric.var <- dat[,numeric.var]
  dat$character.var <- dat[,character.var]
  mean_numeric.var <- mean(dat$numeric.var)
  sd_numeric.var <- sqrt(var(dat$numeric.var))
  dat$numeric.var_std <- (dat$numeric.var - mean_numeric.var)/sd_numeric.var
  #run t-test on original tree data and save p-value and test statistic
  obs.pval <- t.test(dat$numeric.var_std  ~ dat$character.var )$p.value
  obs.res <- t.test((dat$numeric.var_std ~ dat$character.var))$statistic
  
  #get wave and seed for each node
  dat$wave <- get.wave(net)
  dat$seed.id <- get.seed.id(net)
  
  #initialize empty vector to store results
  permuted.res <- rep(NA, iter)
  dat$rec.id2 <- dat$rec.id
  rec <- dat %>% dplyr::select(id, numeric.var_std)
  rec$rec.id2 = rec$id
  dat2 <- dplyr::left_join(dat, rec, by = "rec.id2") %>% dplyr::filter(is.na(numeric.var_std.y)==F)
  r = cor(dat2$numeric.var_std.x, dat2$numeric.var_std.y)
  
  #create new df that will store permuted results
  permute.table <- dat
  #initialize permuted variable
  permute.table$permute.numeric.var <- permute.table$numeric.var_std
  #save values for seeds and set the rest to missing
  permute.table$permute.numeric.var[permute.table$rec.id != 0] <- NA
  #create new df that is ordered by seed and wave so we permute in the correct order
  order.permute.table <- permute.table %>% dplyr::arrange(seed.id, wave)
  
  for(j in 1:iter){
    for(i in 1:dim(order.permute.table)[1]){
      #generate randomized values in first order markov process 
      if(order.permute.table$rec.id[i] != 0){
        rec.id <- order.permute.table$rec.id[i]
        rec.numeric.var <- order.permute.table$permute.numeric.var[order.permute.table$id == rec.id]
        value <- rnorm(1)
        order.permute.table$permute.numeric.var[i] <-  rec.numeric.var*r + value*sqrt(1-r^2)
      }
    }
    permuted.res[j] <- t.test((order.permute.table$permute.numeric.var ~ order.permute.table$character.var))$statistic
    
  }
  
  
  b <- sum(ifelse(abs(permuted.res) >= abs(obs.res), 1, 0))
  p.value <- b/length(permuted.res)
  p.value.mc <- (b+1)/(length(permuted.res)+1)
  
  print(paste0("SPRTCA p-value = ", p.value.mc))
 # print("Homophily for variable 1 = ")
  #print("Homophily for variable 2 = ")
  #return(list(obs.pval, obs.res,p.value.mc, permuted.res,r, mean_numeric.var, sd_numeric.var))
}




```


#### Compare SPRTCA to parametric test
```{r run tests}

#association between age and disease
#ttest
t.test(data_rds$age[data_rds$disease=="Disease"], data_rds$age[data_rds$disease=="No Disease"], var.equal = T)
#SPRTCA
sprtca(1000, "disease", "age", data_rds)

#association between sex and age
#ttest
t.test(data_rds$age[data_rds$sex == "Male"], data_rds$age[data_rds$sex=="Female"], var.equal = T)
#SPRTCA
sprtca(1000, "sex", "age", data_rds)

```

#### Session Info
```{r session info, echo=FALSE}
sessionInfo()
```
